#
# mruby/c  src/Makefile
#
# Copyright (C) 2015-2018 Kyushu Institute of Technology.
# Copyright (C) 2015-2018 Shimane IT Open-Innovation Center.
#
#  This file is distributed under BSD 3-Clause License.
#

clean:
	@rm -rf refcount*
	@rm -rf marksweep*
	@rm -rf bitmap*